apiVersion: batch/v1
kind: CronJob
metadata:
  name: mongo-backup
spec:
  schedule: "0 2 * * *" # every day at 02:00
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: mongodump
              image: mongo:6.0
              command:
                - /bin/sh
                - -c
                - |
                  mongodump \
                    --host=mongo:27017 \
                    --username=$(MONGO_USER) \
                    --password=$(MONGO_PASSWORD) \
                    --authenticationDatabase=admin \
                    --archive=/backup/backup-$(date +%F).gz \
                    --gzip
              env:
                - name: MONGO_USER
                  valueFrom:
                    secretKeyRef:
                      name: mongo-secret
                      key: mongo-root-username
                - name: MONGO_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mongo-secret
                      key: mongo-root-password
              volumeMounts:
                - name: mongo-backup
                  mountPath: /backup
          volumes:
            - name: mongo-backup
              persistentVolumeClaim:
                claimName: mongo-pvc
