apiVersion: v1
kind: Service
metadata:
  name: monitoring-app-service
spec:
  type: LoadBalancer
  selector:
    app: monitoring-app
  ports:
    - protocol: TCP
      port: 80 # public port
      targetPort: 3000 # internal container port
